### PR TITLE
Release fixes

### PR DESCRIPTION
**Pull request by FBartos**
fixes: jasp-stats/jasp-test-release#2293
fixes: jasp-stats/jasp-test-release#2310
fixes: jasp-stats/jasp-test-release#2313
fixes: jasp-stats/jasp-test-release#2316
fixes: jasp-stats/jasp-test-release#2320

### CODE REVIEW

**Comment by juliuspfadt** [comment]
ja, maybe lets just leave it and assume you just created a perfect RNG

**Comment by juliuspfadt** [comment]
what about the failing unit tests

**Comment by juliuspfadt** [comment]
Seems to me like the issues are sufficiently addressed, nice! I suppose we can merge once the unit-tests are in the clear...

**Review by juliuspfadt — APPROVED** [review]

**Comment by FBartos** [comment]
now it should be fixed properly (some stuff that I though was already ordered didn't hold across all possible selections)

**Comment by FBartos** [comment]
(also, the unit tests are not working -- they were written with the old version of the module in mind and I won't be updating them right now)

**Review by juliuspfadt — APPROVED** [review]
@Kucharssim would you merge this even with the failing unit tests?

**Comment by FBartos** [comment]
the unit tests are irrelevant as they weren't updated yet

**Pull request merged**
